var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/todo/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a9822293._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_5bdf2bc8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__146d86fd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__848a4b75._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_todo_page_actions_1258c3f1.js")
R.m(63428)
module.exports=R.m(63428).exports
