var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__762b9ed0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_fd19bc5d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__146d86fd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__848a4b75._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_blog_layout_tsx_5d6ad2d5._.js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_page_actions_cb4aaadc.js")
R.m(94482)
module.exports=R.m(94482).exports
